### ISSUE TITLE
divByZero Unit Test Failing

### ISSUE THREAD

**Issue by EdwardMuturi** [google-developer-training/android-fundamentals#14]
all tests pass except the ``` divByZeroThrows() ``` method

code
``` java
 @Test(expected = IllegalArgumentException.class)
    public void divByZeroThrows() {
       mCalculator.div(32d, 0d);

    }
```
error 
``` java
java.lang.AssertionError: Expected exception: java.lang.IllegalArgumentException

	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by hoanngothanh** [comment]
` @Test(expected = IllegalArgumentException.class)
    public void divByZeroThrows() {
        double resultDiv = mCalculator.div(4d, 0d);
        if (resultDiv == Double.POSITIVE_INFINITY) throw new IllegalArgumentException();
    }`

**Comment by EdwardMuturi** [comment]
thanks
